### ISSUE TITLE
PoneDM support for Android?

### ISSUE THREAD

**Issue by ThePrisonZombie** [Bitl/ponedm-source-sdk-2013-ce#2]
Kinda like it.... But im playing on android tho so since you managed to make it work on linux and pull_OS/Ubuntu , will you make it work for Android too? 

(HL2 is playable in android due to NVIDIA SHIELD port or source engine port by nilleusr [seen on YouTube]) Many people will like this if there is android support for this mod 

(make it as separate file since few modification were made to android source file and people will not get confused with it) BRUH I like it.

**Comment by Bitl** [comment]
not planned
